# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  #- name: Home
  #  url: '#about'
  #  weight: 10
  - name: Projects
    url: '#projects'
    weight: 20
  - name: Publications
    url: '#publication'
    weight: 30
  - name: Talks
    url: '#talks'
    weight: 40
  #- name: Open Research
  #  url: '#open-research'
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 60

# Sub-home menu
  - name: Ephys setup
    url: 'ephys_setup'
    parent: "Open Research"
    weight: 50
  - name: Build microdrive
    url: 'build_microdrive'
    parent: "Open Research"
    weight: 60
  - name: Head-fixed setup
    url: 'head_fixed_setup'
    parent: "Open Research"
    weight: 70
  - name: TES electrode
    url: 'tes_electrode'
    parent: "Open Research"
    weight: 80  
  - name: Optotagging protocol
    url: 'optotagging'
    parent: "Open Research"
    weight: 90
  #- name: Contact
  #  url: '#contact'
  #  parent: "Open Research "
  #  weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/resume.pdf
    weight: 70
